### ISSUE TITLE
Avoid doubling up the main nav if at all possible

### ISSUE THREAD

**Issue by mandiwise** [redacademy/granville-spring-2017#15]
Remember that both menu's mark-up (desktop and mobile versions) will be rendered in the mark-up for the page, which is a bit weird A11Y-wise. See you can use CSS and JS to work around this.

**Comment by kmsolberg** [comment]
Is this because there is a mobile menu and then a desktop menu? 

I did this because the mobile menu has one more menu item than the desktop.

**Comment by rcass** [comment]
Well it is due to use no specifying that the mobile menu should only render on mobile and the desktop should only render not on mobile for example.

Right now the markup for both menus are being generated.
![screen shot 2017-06-23 at 9 50 43 am](https://user-images.githubusercontent.com/5028555/27492082-bed8d83c-57f9-11e7-9f38-7674894a539d.png)

Basically you need to make a solution that results in one menu being rendered at a time. You may find the wordpress function wp_is_mobile() helpful.

**Comment by kmsolberg** [comment]
I deleted the second menu and used CSS to hide the appropriate elements on the main menu.

Commit #065d5ef.

**Comment by rcass** [comment]
Good job Kat! I know this was a tricky one
